apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: bgp-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.24.20.100-172.24.20.110
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: frrleaf2-peer
  namespace: metallb-system
spec:
  myASN: 65002              # ASN of your minikube nodes / MetalLB speakers
  peerASN: 64999            # ASN of your FRR leaf/spine fabric
  peerAddress: 192.168.200.1  # IP of the FRR peer connected to Minikube
  ebgpMultiHop: true          # (Optional, but recommended if L3 adjacency isn't direct)
  holdTime: 180s
  keepaliveTime: 60s
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-advert
  namespace: metallb-system
spec:
  ipAddressPools:
    - bgp-pool
  aggregationLength: 32
